---
- src: git@github.com:Jienshakh/clickhouse-role.git
  scm: git
  name: clickhouse-role 
- src: git@github.com:Jienshakh/vector-role.git
  scm: git
  name: vector-role
- src: git@github.com:Jienshakh/lighthouse-role.git
  scm: git
  name: lighthouse-role

