---
- name: Install ligthouse and Nginx
  hosts: lighthouse
  roles:
    - lighthouse-role
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse-role
- name: Install Vector
  hosts: vector
  vars:
    clickhouse_host: "{{ hostvars['clickhouse-01'].ansible_host }}"
  roles:
    - vector-role
