---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.202.211
            
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.182.49

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.187.176
